#!/usr/bin/env python
# -*- coding: utf-8 -*-

# This file is part of Zeitgeist Borders (https://github.com/fabelier/Zeitgeist-Borders/) 
# Developed by Antoine Mazières, Samuel Huron and Julien Palard.
# Contact : admin at fabelier dot org
#
# Zeitgeist Borders is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Zeitgeist Borders is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Zeitgeist Borders.  If not, see <http://www.gnu.org/licenses/>.

"""
List of all Google's domain names listed at http://www.googlecom/supported_domains
Dictionary built with ./get_google_domains.py
"""

cctlds = {
    "Canada": "ca",
    "Saint Martin": "gp",
    "Sao Tome and Principe": "st",
    "Turkmenistan": "tm",
    "Saint Helena": "sh",
    "Lithuania": "lt",
    "Cambodia": "com.kh",
    "Ethiopia": "com.et",
    "Pridnestrovie (Transnistria)": "md",
    "Argentina": "com.ar",
    "Bolivia": "bo",
    "Bahamas, The": "bs",
    "Burkina Faso": "bf",
    "Bahrain": "com.bh",
    "Saudi Arabia": "com.sa",# Connection timed out
    "Congo, Democratic Republic of the (Congo & Kinshasa)": "cd",
    "Cape Verde": "cv",
    "Slovenia": "si",
    "Guatemala": "com.gt",
    "Bosnia and Herzegovina": "ba",
    "Jordan": "jo",
    "Saint Barthelemy": "gp",
    "Ashmore and Cartier Islands": "com.au",
    "Dominica": "dm",
    "China, Republic of (Taiwan)": "tw",
    "Maldives": "mv",
    "Timor-Leste (East Timor)": "tl",
    "Pakistan": "pk",
    "Oman": "com.om",
    "Tanzania": "co.tz",
    "Seychelles": "sc",
    "Gabon": "ga",
    "Niue": "nu",
    "New Zealand": "co.nz",
    "Jersey": "je",
    "Jamaica": "com.jm",
    "South Ossetia": "ge",
    "Greenland": "gl",
    "Samoa": "ws",
    "Norfolk Island": "com.nf",
    "United Arab Emirates": "ae",
    "India": "in",
    "Azerbaijan": "az",
    "Lesotho": "co.ls",
    "Saint Vincent and the Grenadines": "com.vc",
    "Kenya": "co.ke",
    "Tajikistan": "com.tj",
    "China, People's Republic of": "cn",
    "Turkey": "com.tr",
    "Afghanistan": "af",
    "Bangladesh": "com.bd",
    "Solomon Islands": "com.sb",
    "San Marino": "sm",
    "Mongolia": "mn",
    "France": "fr",
    "Palestinian Territories (Gaza Strip and West Bank)": "ps",
    "Rwanda": "rw",
    "Slovakia": "sk",
    "Somalia": "so",
    "Peru": "com.pe",
    "Laos": "la",
    "Nauru": "nr",
    "Norway": "no",
    "Malawi": "mw",
    "Cook Islands": "co.ck",
    "Benin": "bj",
 #   "Cuba": "com.cu", # Seems blocked : http://www.globalpost.com/dispatch/news/regions/americas/cuba/120627/us-embargo-google-analytics-cuban-internet-access
    "Cameroon": "cm",
    "Montenegro": "me",
    "Togo": "tg",
    "Armenia": "am",
    "Dominican Republic": "com.do",
    "Ukraine": "ua",
    "Ghana": "com.gh",
    "Tonga": "to",
    "Finland": "fi",
    "Libya": "com.ly", #Name or service not known.
    "Somaliland": "so",
    "Indonesia": "co.id",
    "Central African Republic": "cf",
    "Mauritius": "mu",
    "Liechtenstein": "li",
    "Belarus": "by",
    "British Virgin Islands": "vg",
    "Mali": "ml",
    "Russia": "ru",
    "Bulgaria": "bg",
    "United States": "com",
    "Romania": "ro",
    "Angola": "co.ao",
    "Chad": "td",
    "South Africa": "co.za",
    "Tokelau": "tk",
    "Cyprus": "com.cy",
    "Sweden": "se",
    "Qatar": "com.qa",
    "Malaysia": "com.my",
    "Austria": "at",
    "Vietnam": "vn",
    "Mozambique": "co.mz",
    "Uganda": "ug",
    "Hungary": "hu",
    "Niger": "ne",
    "Isle of Man": "im",
    "Brazil": "com.br",
    "U.S. Virgin Islands": "co.vi",
    "Kuwait": "com.kw",
    "Panama": "com.pa",
    "Guyana": "gy",
    "Costa Rica": "co.cr",
    "Luxembourg": "lu",
    "American Samoa": "as",
    "Andorra": "ad",
    "Gibraltar": "com.gi",
    "Ireland": "ie",
    "Nigeria": "ng",
    "Ecuador": "ec",
    "Czech Republic": "cz",
    "Brunei": "com.bn",
    "Australia": "com.au",
    "Vanuatu": "vu",
    "Algeria": "dz",
    "El Salvador": "com.sv",
    "Pitcairn Islands": "pn",
    "Congo, Republic of the (Congo & Brazzaville)": "cg",
    "Chile": "cl",
    "Puerto Rico": "pr",
    "Belgium": "be",
    "Kiribati": "ki",
    "Haiti": "ht",
    "Belize": "bz",
    "Hong Kong": "hk",
    "Sierra Leone": "sl",
    "Georgia": "ge",
    "Denmark": "dk",
    "Philippines": "ph",
    "Moldova": "md",
    "Morocco": "ma",
    "Croatia": "hr",
    "Micronesia": "fm",
    "Guernsey": "gg",
    "Thailand": "co.th",
    "Switzerland": "ch",
    "Korea, Republic of  (South Korea)": "kr",
    "Iraq": "iq",
    "Portugal": "pt",
    "Estonia": "ee",
    "Uruguay": "com.uy",
    "Lebanon": "com.lb",
    "Northern Cyprus": "com.tr",
    "Uzbekistan": "uz",
    "Tunisia": "tn",
    "Djibouti": "dj",
    "Antigua and Barbuda": "ag",
    "Spain": "es",
    "Colombia": "co",
    "Burundi": "bi",
    "Fiji": "com.fj",
    "Madagascar": "mg",
    "Italy": "it",
    "Nepal": "com.np",
    "Malta": "com.mt",
    "Netherlands": "nl",
    "Anguilla": "com.ai",
    "Venezuela": "co.ve",
    "Cote d'Ivoire (Ivory Coast)": "ci",
    "Israel": "co.il",
    "Iceland": "is",
    "Zambia": "co.zm",
    "Senegal": "sn",
    "Trinidad and Tobago": "tt",
    "Zimbabwe": "co.zw",
    "Germany": "de",
    "Abkhazia": "ge",
    "Kazakhstan": "kz",
    "Poland": "pl",
    "Kyrgyzstan": "kg",
    "Montserrat": "ms",
    "Coral Sea Islands": "com.au",
    "Macedonia": "mk",
    "Sri Lanka": "lk",
    "Latvia": "lv",
    "Japan": "jp",
    "Guadeloupe": "gp",
    "Honduras": "hn",
    "Mexico": "mx",
    "Egypt": "com.eg",
    "Nicaragua": "com.ni",
    "Singapore": "sg",
    "Serbia": "rs",
    "United Kingdom": "co.uk",
    "Gambia, The": "gm",
    "Greece": "gr",
    "Paraguay": "com.py",
    "Namibia": "com.na",
    "Nagorno-Karabakh": "az",
    "Botswana": "co.bw",
}
